### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by Moonyol** [IsAvaible/AngularModUpdater#2]
It can put duplicate mods onto the list if they are different versions of the same mod, this could be fixed by looking at their mod ids
![image](https://github.com/IsAvaible/AngularModUpdater/assets/92951072/65104542-2380-4293-bfa1-d9c7ae3c987c)

**Comment by IsAvaible** [comment]
This should not happen, as files grouped under the same project ID should appear in a single card. Could you provide steps to reproduce this bug?

**Comment by Moonyol** [comment]
I can't reproduce it anymore, maybe it was fixed. Although, I did have around a thousand mods in it when it happened.
