### ISSUE TITLE
doesnt work 

### ISSUE THREAD

**Issue by ah1mao** [IsAvaible/AngularModUpdater#4]
doesnt work 
ape

**Comment by IsAvaible** [comment]
Hi there! Thank you for reaching out. Could you please provide more details about the issue you're experiencing with the Mod Updater? Specifically, it would help if you could answer some of the following questions:

- Which mod loader (Fabric, Forge, or Quilt) are you using?
- Which Minecraft version are you targeting?
- How many mods are you trying to upload?
- Did you encounter any error messages, or does the tool not respond at all?
- Have you checked if you've hit Modrinth's rate limit?

In the meantime, here are some common troubleshooting tips that might help:

- Ensure you're uploading the correct .jar files for your mods.
- Double-check that your internet connection is stable, as the tool relies on the Modrinth API.
- If you have many mods, try uploading fewer mods at once to see if that resolves the issue.
- Wait a few seconds and try again if you hit the rate limit (maximum ~290 mods per minute).

Looking forward to your response so we can help you resolve this!

**Comment by IsAvaible** [comment]
Hi! Since there hasn’t been any activity on this ticket for the past six weeks, I’ll go ahead and close it for now. If any issues come up, please feel free to reopen it or create a new ticket.
