### ISSUE TITLE
neoforge support?

### ISSUE THREAD

**Issue by Geniusssmit** [IsAvaible/AngularModUpdater#5]
1.21.1 has a lot of mods for neoforge. Do you plan on implementing it?

**Comment by IsAvaible** [comment]
Just implemented a [patch](https://github.com/IsAvaible/AngularModUpdater/commit/444e6e49af47bb1843e05f00be9af5a741a0a767), which should be live in a few minutes. Please let me know whether this works for you (You may need to refresh the site once after visiting to receive the update).

**Comment by Geniusssmit** [comment]
it works, thank you!

**Comment by IsAvaible** [comment]
Great, glad I could help!
