### ISSUE TITLE
.mrpack support?

### ISSUE THREAD

**Issue by notrohit1702** [IsAvaible/AngularModUpdater#7]
Is it possible to implement modrinth modpack (mrpack) support, would be really helpful for me!

**Comment by notrohit1702** [comment]
Also, I'm guessing it's not possible to implement automatically splitting a large number of mods into smaller batches and doing those batches at a slower (but automatic) rate? I don't know much about how APIs work so this is probably really dumb, sorry.

**Comment by IsAvaible** [comment]
Hey! I [just added .mrpack support](https://github.com/IsAvaible/AngularModUpdater/commit/8653c941d17cdd565e0a0ac865130d94c2b763eb), so now you should be able to update modpack files just like you update individual mods on the website.

![image](https://github.com/user-attachments/assets/608366ef-179b-447e-9e76-becba540b322)

Could you let me know if this works on your end? (You might need to force-refresh the site with [CTRL] + [SHIFT] + [R] to see the update.)

As for your second question, I’d like to understand a bit more about your needs around splitting large batches of mods into smaller, automated ones. Could you share what issues you’re encountering with the current setup?

Thanks!

**Comment by notrohit1702** [comment]
> Hey! I [just added .mrpack support](https://github.com/IsAvaible/AngularModUpdater/commit/8653c941d17cdd565e0a0ac865130d94c2b763eb), so now you should be able to update modpack files just like you update individual mods on the website.
> 
> ![image](https://private-user-images.githubusercontent.com/76125864/380510317-608366ef-179b-447e-9e76-becba540b322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjcyMDAsIm5iZiI6MTczMDEyNjkwMCwicGF0aCI6Ii83NjEyNTg2NC8zODA1MTAzMTctNjA4MzY2ZWYtMTc5Yi00NDdlLTllNzYtYmVjYmE1NDBiMzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDE0NDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMzRhMjQzYjA0NWVjODEzYzRjM2ZhYzUzMTU1YjEzOTgzNDQ0YWIxNGFlODY3YTlhMWQwYmI2OWIwZmMyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B0tZICG_iQ2KHyfl1wGJjTaTAl_2EruK6NjxTcLD47c)
> 
> Could you let me know if this works on your end? (You might need to force-refresh the site with [CTRL] + [SHIFT] + [R] to see the update.)
> 
> As for your second question, I’d like to understand a bit more about your needs around splitting large batches of mods into smaller, automated ones. Could you share what issues you’re encountering with the current setup?
> 
> Thanks!

Hey! The modpack update feature works like you said, after a hard refresh. However, I meant more of updating each mod included in the modpack's `modrinth.index.json` file, as a tool for modpack *creators* and not for updating them from the current releases.

As for the automatic batch-splitting feature, when I try to update a large number of mods (138 to be exact) at once, the progress bar goes up to ~20-30% (sometimes stays at 0% too) and then stops. Splitting them into smaller sets (10 mods at a time seems to work reliably) and updating each set one by one works for me.

![Stuck progress bar](https://github.com/user-attachments/assets/fc28455c-2d44-4ba1-96cd-ed6c1fe794f4)

If there was an option to automatically do this without user interference, it would reduce the work required to update a large modpack.

Once again, I don't know a lot about how APIs work, so this might sound incredibly naive.

**Comment by IsAvaible** [comment]
Hi! I have mode some changes to the site, adding file batching and the ability to parse and load mods from modrinth.index.json files.

Please let me know whether this fixes your networking issues. I have tested the current version with Chromes 3G throttling preset (750kB/s, 100RTT).

As last time, you might need to force-refresh the site with [CTRL] + [SHIFT] + [R] to receive the update.

**Comment by notrohit1702** [comment]
> Hi! I have mode some changes to the site, adding automatic file batching and the ability to parse and load mods from modrinth.index.json files.
> 
> Please let me know whether this fixes your networking issues. I have tested the current version with Chromes 3G throttling preset (750kB/s, 100RTT).
> 
> As last time, you might need to force-refresh the site with [CTRL] + [SHIFT] + [R] to receive the update.

Its works wonderfully. Thank you so much for implementing this!

**Comment by IsAvaible** [comment]
Happy to help!
