### ISSUE TITLE
Changelog viewing feature

### ISSUE THREAD

**Issue by hjake123** [IsAvaible/AngularModUpdater#8]
It would be nice to be able to see the changelog of the chosen version (or maybe every version between the uploaded one and the chosen one, if that is feasible).

**Comment by IsAvaible** [comment]
Hey @hjake123,

it's currently possible to see the changelog by clicking the last updated widget.

![image](https://github.com/user-attachments/assets/2f93972c-d52e-45f5-b821-906b75a5b5f3)

It's true though that this functionality is a bit hidden. I will try to improve the UX in the coming days and add the ability to quickly browse through all changelogs for all versions, as the data is available to me anyway.

**Comment by hjake123** [comment]
Ah, alright! Feel free to close this issue then
